#!/bin/sh
set -eu

command_name=$1
shift

case "$command_name" in
    list)
        test "${1:-}" = systemproperties || exit 2
        printf 'Default machine folder: %s\n' "${TEST_VM_DIRECTORY%/*}"
        ;;
    showvminfo)
        if test -f "$TEST_STATE_PATH/vm-state"; then
            vm_state=$(sed -n '1p' "$TEST_STATE_PATH/vm-state")
        else
            exit 1
        fi
        if test "${2:-}" = "--machinereadable"; then
            printf 'VMState="poweroff"\n'
            printf 'CfgFile="%s/infinityos-4.vbox"\n' "$TEST_VM_DIRECTORY"
            if test "$vm_state" = new; then
                printf 'platformArchitecture="ARM"\n'
                printf 'ostype="Other/Unknown (ARM 64-bit)"\n'
                printf 'memory=%s\n' "$(sed -n '1p' "$TEST_STATE_PATH/memory")"
                printf 'cpus=%s\n' "$(sed -n '1p' "$TEST_STATE_PATH/cpus")"
                printf 'graphicscontroller="%s"\n' "$(sed -n '1p' "$TEST_STATE_PATH/graphics")"
                printf 'usb="off"\n'
                printf 'xhci="on"\n'
                printf 'dvd="%s"\n' "$TEST_ISO_PATH"
            fi
        else
            mouse_mode=$(sed -n '1p' "$TEST_STATE_PATH/mouse")
            if test "$mouse_mode" = usb; then
                printf 'Pointing Device:             USB Mouse\n'
            else
                printf 'Pointing Device:             PS/2 Mouse\n'
            fi
            printf 'Keyboard Device:             USB Keyboard\n'
            printf 'xHCI USB:                    enabled\n'
        fi
        ;;
    unregistervm)
        : > "$TEST_STATE_PATH/unregistered"
        rm -f "$TEST_STATE_PATH/vm-state"
        if test -f "$TEST_STATE_PATH/recovered-registration"; then
            rm -f "$TEST_VM_DIRECTORY/infinityos-4.vbox" "$TEST_VM_DIRECTORY/infinityos-4.vdi"
            rmdir "$TEST_VM_DIRECTORY" 2>/dev/null || true
            rm -f "$TEST_STATE_PATH/recovered-registration"
        fi
        ;;
    registervm)
        test "$1" = "$TEST_VM_DIRECTORY/infinityos-4.vbox" || exit 3
        : > "$TEST_STATE_PATH/recovered-registration"
        printf 'old\n' > "$TEST_STATE_PATH/vm-state"
        ;;
    createvm)
        mkdir -p "$TEST_VM_DIRECTORY"
        : > "$TEST_VM_DIRECTORY/infinityos-4.vbox"
        printf 'new\n' > "$TEST_STATE_PATH/vm-state"
        ;;
    showmediuminfo)
        : > "$TEST_STATE_PATH/medium-inspected"
        test "$TEST_MEDIUM_MODE" = attached
        ;;
    closemedium)
        : > "$TEST_STATE_PATH/close-attempted"
        exit 1
        ;;
    createmedium)
        while test "$#" -gt 0; do
            if test "$1" = "--filename"; then
                shift
                disk_path=$1
                break
            fi
            shift
        done
        test ! -e "$disk_path" || exit 1
        printf 'fresh\n' > "$disk_path"
        ;;
    modifyvm)
        while test "$#" -gt 0; do
            case "$1" in
                --tpm-type)
                    shift
                    test "$1" = 2.0 || exit 3
                    printf '200\n' > "$TEST_STATE_PATH/tpm-version"
                    ;;
                --memory)
                    shift
                    printf '%s\n' "$1" > "$TEST_STATE_PATH/memory"
                    ;;
                --cpus)
                    shift
                    printf '%s\n' "$1" > "$TEST_STATE_PATH/cpus"
                    ;;
                --boot1|--boot2)
                    boot_option=$1
                    shift
                    printf '%s\n' "$1" > "$TEST_STATE_PATH/$boot_option"
                    ;;
                --graphicscontroller)
                    shift
                    printf '%s\n' "$1" > "$TEST_STATE_PATH/graphics"
                    ;;
                --mouse)
                    shift
                    printf '%s\n' "$1" > "$TEST_STATE_PATH/mouse"
                    ;;
            esac
            shift
        done
        ;;
    controlvm|setextradata|storagectl|storageattach)
        ;;
    *)
        exit 2
        ;;
esac
