#ifndef INFINITY_COMPILER_TARGET_H
#define INFINITY_COMPILER_TARGET_H
#define _GNU_SOURCE 1
#define _POSIX_THREADS 1
#define _UNIX98_THREAD_MUTEX_ATTRIBUTES 1
#define _POSIX_TIMERS 1
#define _POSIX_MONOTONIC_CLOCK 200809L
#define __INFINITY__ 1
#endif
