[package]
name = "infinity-servo-memory-probe"
version = "0.1.0"
edition = "2021"
publish = false

[features]
context-probe = []
executor-probe = ["context-probe"]
std-probe = ["executor-probe", "infinity-servo-runtime-primitives/native-abi"]
mio-probe = ["std-probe", "dep:mio"]

[workspace]

[lib]
path = "probe.rs"
crate-type = ["staticlib"]

[dependencies]
infinity-servo-runtime-primitives = { path = "../../../sdk/servo-runtime-primitives" }
mio = { path = "../../../build/servo-native-deps/mio-1.2.3", optional = true, default-features = false, features = ["os-poll"] }

[profile.release]
panic = "abort"
opt-level = 2
