/* Keep this provider's narrow C support private to its own symbol namespace. */
#define strlen infinity_flite_strlen
#define strcmp infinity_flite_strcmp
#define strncmp infinity_flite_strncmp
#define strcpy infinity_flite_strcpy
#define strncpy infinity_flite_strncpy
#define strcat infinity_flite_strcat
#define strchr infinity_flite_strchr
#define strrchr infinity_flite_strrchr
#define strstr infinity_flite_strstr
#define memcpy infinity_flite_memcpy
#define memmove infinity_flite_memmove
#define memset infinity_flite_memset
#define memcmp infinity_flite_memcmp
#define atoi infinity_flite_atoi
#define atof infinity_flite_atof
#define abs infinity_flite_abs
#define rand infinity_flite_rand
#define fabs infinity_flite_fabs
#define exit infinity_flite_exit
#define abort infinity_flite_abort
#define isalpha infinity_flite_isalpha
#define isalnum infinity_flite_isalnum
#define isdigit infinity_flite_isdigit
#define isspace infinity_flite_isspace
#define isupper infinity_flite_isupper
#define islower infinity_flite_islower
#define ispunct infinity_flite_ispunct
#define toupper infinity_flite_toupper
#define tolower infinity_flite_tolower
#define snprintf infinity_flite_snprintf
#define stdout infinity_flite_stdout
#define stdin infinity_flite_stdin
#define stderr infinity_flite_stderr
